<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260518091624 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Utensil and Category entities in macuisine and link them to Recipe';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64C19C1B03A8386 ON category (created_by_id)');
        $this->addSql('CREATE TABLE recipe_utensil (recipe_id INT NOT NULL, utensil_id INT NOT NULL, PRIMARY KEY (recipe_id, utensil_id))');
        $this->addSql('CREATE INDEX IDX_D3CC32FC59D8A214 ON recipe_utensil (recipe_id)');
        $this->addSql('CREATE INDEX IDX_D3CC32FCEC4313DE ON recipe_utensil (utensil_id)');
        $this->addSql('CREATE TABLE utensil (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9F283CBCB03A8386 ON utensil (created_by_id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_utensil ADD CONSTRAINT FK_D3CC32FC59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recipe_utensil ADD CONSTRAINT FK_D3CC32FCEC4313DE FOREIGN KEY (utensil_id) REFERENCES utensil (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utensil ADD CONSTRAINT FK_9F283CBCB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe ADD category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE recipe ADD CONSTRAINT FK_DA88B13712469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('CREATE INDEX IDX_DA88B13712469DE2 ON recipe (category_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1B03A8386');
        $this->addSql('ALTER TABLE recipe_utensil DROP CONSTRAINT FK_D3CC32FC59D8A214');
        $this->addSql('ALTER TABLE recipe_utensil DROP CONSTRAINT FK_D3CC32FCEC4313DE');
        $this->addSql('ALTER TABLE utensil DROP CONSTRAINT FK_9F283CBCB03A8386');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE recipe_utensil');
        $this->addSql('DROP TABLE utensil');
        $this->addSql('ALTER TABLE recipe DROP CONSTRAINT FK_DA88B13712469DE2');
        $this->addSql('DROP INDEX IDX_DA88B13712469DE2');
        $this->addSql('ALTER TABLE recipe DROP category_id');
    }
}
