<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429093225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add tables for Recipe, Ingredient and RefRecipeIngredient entities';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, name VARCHAR(15) NOT NULL, description VARCHAR(600) NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DA88B137F675F31B ON recipe (author_id)');
        $this->addSql('CREATE TABLE ref_recipe_ingredient (quantity DOUBLE PRECISION NOT NULL, unite VARCHAR(10) NOT NULL, recipe_id INT NOT NULL, ingredient_id INT NOT NULL, PRIMARY KEY (recipe_id, ingredient_id))');
        $this->addSql('CREATE INDEX IDX_F6BC88A059D8A214 ON ref_recipe_ingredient (recipe_id)');
        $this->addSql('CREATE INDEX IDX_F6BC88A0933FE08C ON ref_recipe_ingredient (ingredient_id)');
        $this->addSql('ALTER TABLE recipe ADD CONSTRAINT FK_DA88B137F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ref_recipe_ingredient ADD CONSTRAINT FK_F6BC88A059D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ref_recipe_ingredient ADD CONSTRAINT FK_F6BC88A0933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipe DROP CONSTRAINT FK_DA88B137F675F31B');
        $this->addSql('ALTER TABLE ref_recipe_ingredient DROP CONSTRAINT FK_F6BC88A059D8A214');
        $this->addSql('ALTER TABLE ref_recipe_ingredient DROP CONSTRAINT FK_F6BC88A0933FE08C');
        $this->addSql('DROP TABLE ingredient');
        $this->addSql('DROP TABLE recipe');
        $this->addSql('DROP TABLE ref_recipe_ingredient');
    }
}
