<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Add Bmi and Measurement entities with relations to User entity
 */
final class Version20260427192719 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Bmi and Measurement entities with relations to User entity';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bmi (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, height DOUBLE PRECISION NOT NULL, weight DOUBLE PRECISION NOT NULL, bmi DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_502F0A4AA76ED395 ON bmi (user_id)');
        $this->addSql('CREATE TABLE measurement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chest DOUBLE PRECISION NOT NULL, hips DOUBLE PRECISION NOT NULL, thigh DOUBLE PRECISION NOT NULL, waist DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2CE0D811A76ED395 ON measurement (user_id)');
        $this->addSql('ALTER TABLE bmi ADD CONSTRAINT FK_502F0A4AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE measurement ADD CONSTRAINT FK_2CE0D811A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bmi DROP CONSTRAINT FK_502F0A4AA76ED395');
        $this->addSql('ALTER TABLE measurement DROP CONSTRAINT FK_2CE0D811A76ED395');
        $this->addSql('DROP TABLE bmi');
        $this->addSql('DROP TABLE measurement');
    }
}
