<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426174347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user and relationship tables';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE relationship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user1_id INT NOT NULL, user2_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_200444A056AE248B ON relationship (user1_id)');
        $this->addSql('CREATE INDEX IDX_200444A0441B8B65 ON relationship (user2_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(30) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE relationship ADD CONSTRAINT FK_200444A056AE248B FOREIGN KEY (user1_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relationship ADD CONSTRAINT FK_200444A0441B8B65 FOREIGN KEY (user2_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE relationship DROP CONSTRAINT FK_200444A056AE248B');
        $this->addSql('ALTER TABLE relationship DROP CONSTRAINT FK_200444A0441B8B65');
        $this->addSql('DROP TABLE relationship');
        $this->addSql('DROP TABLE "user"');
    }
}
